/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MagicString {
  constructor(str: string)
  append(input: string): this
  appendLeft(index: number, input: string): this
  insertLeft(index: number, input: string): this
  appendRight(index: number, input: string): this
  prepend(input: string): this
  prependLeft(index: number, input: string): this
  prependRight(index: number, input: string): this
  insertRight(index: number, input: string): this
  trim(charType?: string | undefined | null): this
  trimLines(): this
  trimStart(charType?: string | undefined | null): this
  trimEnd(charType?: string | undefined | null): this
  move(start: number, end: number, index: number): this
  toString(): string
}
