/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OverwriteOptions {
  contentOnly?: boolean
  storeName?: boolean
  overwrite?: boolean
}
export declare class MagicString {
  constructor(str: string)
  insert(): void
  append(input: string): this
  appendLeft(index: number, input: string): this
  insertLeft(index: number, input: string): this
  appendRight(index: number, input: string): this
  prepend(input: string): this
  prependLeft(index: number, input: string): this
  prependRight(index: number, input: string): this
  insertRight(index: number, input: string): this
  trim(charType?: string | undefined | null): this
  trimLines(): this
  trimStart(charType?: string | undefined | null): this
  trimEnd(charType?: string | undefined | null): this
  move(start: number, end: number, index: number): this
  remove(start: number, end: number): this
  overwrite(
    start: number,
    end: number,
    content: string,
    options?: OverwriteOptions
  ): this
  update(
    start: number,
    end: number,
    content: string,
    options?: OverwriteOptions
  ): this
  isEmpty(): boolean
  toString(): string
  hasChanged(): boolean
  clone(): MagicString
  snip(start: number, end: number): MagicString
  reset(start: number, end: number): this
  replace(searchValue: string, replacement: string): this
  replaceAll(searchValue: string, replacement: string): this
}
