/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GenerateMapOptions {
  file?: string
  source?: string
  sourceRoot?: string
  includeContent?: boolean
  hires?: boolean
}
export interface OverwriteOptions {
  contentOnly?: boolean
  storeName?: boolean
  overwrite?: boolean
}
export interface MagicStringOptions {
  filename?: string
  indentExclusionRanges?: Array<number>
  ignoreList?: boolean
}
export interface JsRegExp {
  global?: boolean
  rule: string
}
export declare class MagicString {
  constructor(str: string, options?: MagicStringOptions | undefined | null)
  insert(): void
  append(input: string): this
  appendLeft(index: number, input: string): this
  insertLeft(index: number, input: string): this
  appendRight(index: number, input: string): this
  prepend(input: string): this
  prependLeft(index: number, input: string): this
  prependRight(index: number, input: string): this
  insertRight(index: number, input: string): this
  trim(charType?: string | undefined | null): this
  trimLines(): this
  trimStart(charType?: string | undefined | null): this
  trimEnd(charType?: string | undefined | null): this
  move(start: number, end: number, index: number): this
  remove(start: number, end: number): this
  overwrite(
    start: number,
    end: number,
    content: string,
    options?: OverwriteOptions
  ): this
  update(
    start: number,
    end: number,
    content: string,
    options?: OverwriteOptions
  ): this
  isEmpty(): boolean
  toString(): string
  hasChanged(): boolean
  clone(): MagicString
  snip(start: number, end: number): MagicString
  slice(
    start?: number | undefined | null,
    end?: number | undefined | null
  ): string
  reset(start: number, end: number): this
  replace(
    searchValue: string | JsRegExp,
    replacement: string | ((...args: any[]) => any)
  ): this
  replaceAll(
    searchValue: string | JsRegExp,
    replacement: string | ((...args: any[]) => any)
  ): this
  generateMap(options?: GenerateMapOptions | undefined | null): SourceMap
  generateDecodedMap(
    options?: GenerateMapOptions | undefined | null
  ): DecodedMap
}
export declare class DecodedMap {
  version: number
  file?: string
  sourceRoot?: string
  sources: Array<string>
  sourcesContent?: Array<string>
  names: Array<string>
  mappings: Array<number>
  xGoogleIgnoreList?: Array<number>
}
export declare class SourceMap {
  version: number
  file?: string
  sourceRoot?: string
  sources: Array<string>
  sourcesContent?: Array<string>
  names: Array<string>
  mappings: string
  xGoogleIgnoreList?: Array<number>
  toString(): string
  toUrl(): string
}
